spring.datasource.url=jdbc:mysql://localhost:3306/agri_smart
spring.datasource.username=root
spring.datasource.password=bhanu

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8081